version: '2'
services:
  elasticsearch:
    image: elasticsearch:7.5.0
    environment:
      - discovery.type=single-node
    networks:
      - atrix-elasticsearch_test
    ports:
      - 9200:9200

networks:
  atrix-elasticsearch_test:
    driver: bridge
